version: "3.4"

services:
  bitcoind:
    build: .
    container_name: bitcoind
    environment:
      RUN_ARGS: "-conf=/config/bitcoin.conf -datadir=/data"
    ports:
      - 8332:8332/tcp
      - 8334:8334/tcp
    networks:
      - shared
    volumes:
      - ./config/${network:-mainnet}:/config
      - "${host_data_dir:-bitcoind-data}:/data"
    restart: unless-stopped

networks:
  shared:

volumes:
  bitcoind-data:
