version: "3.4"

services:
  dogecoind:
    build: .
    container_name: dogecoind
    environment:
      RUN_ARGS: "-conf=/config/dogecoin.conf -datadir=/data"
    ports:
      - 28332:8332/tcp
      - 28334:8334/tcp
    networks:
      - shared
    volumes:
      - ./config/${network:-mainnet}:/config
      - "${host_data_dir:-dogecoind-data}:/data"
    restart: unless-stopped

networks:
  shared:

volumes:
  dogecoind-data:
