version: "3.4"

volumes:
  dogecoind-data:

services:
  dogecoind:
    build: .
    container_name: dogecoind
    environment:
      RUN_ARGS: "-conf=/config/dogecoin.conf -datadir=/data"
    ports:
      - 8332:8332/tcp
      - 8334:8334/tcp
    volumes:
      - ./config/${network:-mainnet}:/config
      - "${host_data_dir:-dogecoind-data}:/data"
    restart: unless-stopped
