version: "3.4"

volumes:
  bitcoin-abc-data:

services:
  bitcoin-abc:
    build: .
    container_name: bitcoin-abc
    environment:
      RUN_ARGS: "-conf=/config/bitcoin-abc.conf -datadir=/data"
    ports:
      - 18332:8332/tcp
      - 18334:8334/tcp
    volumes:
      - ./config/${network:-mainnet}:/config
      - "${host_data_dir:-bitcoin-abc-data}:/data"
    restart: unless-stopped
