version: "3.4"

services:
  litecoind:
    build: .
    container_name: litecoind
    environment:
      RUN_ARGS: "-conf=/config/litecoin.conf -datadir=/data -rpcallowip=0.0.0.0/0"
    ports:
      - 9332:9332/tcp
    networks:
      - shared
    volumes:
      - ./config/${network:-mainnet}:/config
      - "${host_data_dir:-litecoind-data}:/data"
    restart: unless-stopped

networks:
  shared:

volumes:
  litecoind-data:
