version: "3.4"

services:
  avalanchego:
    build: .
    container_name: avalanchego
    environment:
      RUN_ARGS: "--config-file=/config/config.json --chain-config-dir=/config/C"
    ports:
      - 9650:9650/tcp
    networks:
      - shared
    volumes:
      - ./config/${network:-mainnet}:/config
      - "${host_data_dir:-avalanchego-data}:/root/.avalanchego"
    restart: unless-stopped

networks:
  shared:

volumes:
  avalanchego-data:
