name: Containers Continuous-Deployment
run-name: CD ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [ main ]
jobs:
  Build-Deploy-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Identify changed application subdirectories
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_max_depth: "1"
          files_ignore: .github

      - name: Build modified application Docker images
        run: |
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            version=$(cat $dir/version.txt)
            docker build $dir/ --file $dir/Dockerfile --build-arg VERSION=$version --tag 0labs/$dir:$version
          done

      - name: Login to Dockerhub for release
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USR }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PWD }}
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin

      - name: Publish Docker image
        run: |
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            version=$(cat $dir/version.txt)
            docker push 0labs/$dir:$version
          done
