name: Containers Continuous-Integration
run-name: CI ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  Build-Test-Container-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Identify changed application subdirectories
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_max_depth: "1"
          dir_names_exclude_root: "true"
          files_ignore: |
            .github
            docs

      - name: Build modified application Docker images
        run: |
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            version=$(cat $dir/version.txt)
            docker build $dir/ --file $dir/Dockerfile --build-arg VERSION=$version --tag 0labs/$dir:$version
          done

      - name: Test application docker-compose setups
        run: |
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            docker-compose -f $dir/docker-compose.yaml up -d --build
            docker-compose -f $dir/docker-compose.yaml down
          done
      - name: Update application Dockerhub READMEs
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USR }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PWD }}
        run: |
          python -m pip install --upgrade pip
          pip install jinja-cli
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            export name=$dir
            export version="$(cat $dir/version.txt)"
            echo "Version: ${version}"

            export version_info=$( { docker run --rm -e RUN_ARGS=--version 0labs/$dir:$version; } 2>&1)
            export cli_args=$( { docker run --rm -e RUN_ARGS=--help 0labs/$dir:$version; } 2>&1)
            jinja -E name -E version_info -E cli_args docs/dockerhub-readme.md.j2 -o dockerhub-readme-$dir.md

            docker run --rm -v $(pwd)/dockerhub-readme-$dir.md:/data/README.md \
              -e DOCKERHUB_USR=$DOCKERHUB_USER \
              -e DOCKERHUB_PWD=$DOCKERHUB_PASSWORD \
              -e DOCKERHUB_ORG=0labs \
              -e DOCKERHUB_REPO=$dir gofunky/readmyhub:stable
          done
