name: Containers Continuous-Integration
run-name: CI ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [ main ]
  pull_request:
env:
  AVAX_VERSION: v1.9.7
jobs:
  Build-Test-Container-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build application Docker image
        run: docker build avalanchego/ --file avalanchego/Dockerfile --build-arg VERSION=$AVAX_VERSION --tag 0labs/avalanchego:$AVAX_VERSION

      - name: Test docker-compose 🚀
        run: docker-compose -f avalanchego/docker-compose.yaml up -d --build

