name: Auto detect and update container applications 
run-name: main - twice daily
on:
  pull_request:
  schedule:
    - cron: '00 01,13 * * *'
jobs:
  Container-Auto-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Detect application version changes
        run: |
          python -m pip install --upgrade pip
          pip install yq jq

          for dir in */; do
            echo "${dir} found."
            if [[ -f "$dir/meta.yml" ]]; then
              version=$(cat $dir/meta.yml | yq .version)
              latest_release_url=$(cat $dir/meta.yml | yq .latest_release_url | sed "s/\"//g")
              echo "url: $latest_release_url"
              latest_version=$(curl -s $latest_release_url | jq .tag_name)

              echo "latest version: $latest_version"
              echo "current version: $version"

              if [[ "$version" != "$latest_version" ]]; then
                echo "Version mismatch found."

                # TODO: remove once version.txt has been deprecated
                echo $latest_version > $dir/version.txt
                yq -yi ".version=$latest_version" $dir/meta.yml
              fi
            fi
          done

      - name: Commit detected version updates
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'O1bot: commiting version updates'
          add: '*meta.yml'
          new_branch: app-version-updates
