---
name: Auto detect and update container applications
run-name: main - twice daily
on:
  schedule:
    - cron: "00 01,13 * * *"
jobs:
  Container-Auto-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Detect application version changes
        run: |
          python -m pip install --upgrade pip
          pip install yq jq

          for dir in */; do
            echo "${dir} found."
            if [[ -f "$dir/meta.yml" ]]; then
              version=$(cat $dir/meta.yml | yq -r .version)
              latest_release_url=$(cat $dir/meta.yml | yq -r .latest_release_url)
              echo "url: $latest_release_url"
              latest_version=$(curl -s $latest_release_url | jq -r .tag_name)

              echo "latest version: $latest_version"
              echo "current version: ${version}"
              if [[ "${version/v/}" == "${latest_version/v/}" ]]; then
                echo "${dir}: Current version is at the latest"
              else
                echo "Version mismatch found."

                # TODO: remove once version.txt has been deprecated
                echo ${latest_version/v/} > $dir/version.txt
                yq -yi ".version=\"${latest_version/v/}\"" $dir/meta.yml
              fi
            fi
          done

      - name: Commit detected version updates
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "O1bot: commiting version updates"
          add: "*meta.yml *version.txt"
          new_branch: app-version-updates
          push: origin app-version-updates --force
